server:
  port: 8070

spring:
  # Resource server configurations
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/auth/realms/spring-security-example
          jwk-set-uri: http://localhost:8085/auth/realms/spring-security-example/protocol/openid-connect/certs

  jackson:
    default-property-inclusion: NON_NULL
    property-naming-strategy: SNAKE_CASE
    serialization.INDENT_OUTPUT: false
    serialization:
      write-dates-as-timestamps: true

  data:
    cassandra:
      keyspace-name: ratedb
      contact-points: 127.0.0.1
      local-datacenter: datacenter1

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer



management:
  server:
    port: 8071
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
