version: '3.9'

services:

  cassandra:
    container_name: movie_challenge_cassandra
    build: cassandra/
    mem_reservation: 1024M
    ports:
        - "7000:7000"
        - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=moviedb

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
      image: 'bitnami/kafka:latest'
      ports:
        - '9092:9092'
      environment:
        - KAFKA_BROKER_ID=1
        - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
        - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
        - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
        - ALLOW_PLAINTEXT_LISTENER=yes
      depends_on:
        - zookeeper

  keycloak:
    image: jboss/keycloak:16.1.1
    restart: on-failure
    command:
      - "-b"
      - "0.0.0.0"
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=singleFile"
      - "-Dkeycloak.migration.file=/keycloak/config/import.json"
      - "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING"
    volumes:
      - ./keycloak/config:/keycloak/config/
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
      - DB_VENDOR=postgres
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_ADDR=postgres
      - DB_PORT=5432
      - DB_DATABASE=keycloakdb
    ports:
      - "8085:8080"
    depends_on:
      - postgres

  postgres:
    build: postgres/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_MULTIPLE_DATABASES=keycloakdb,bestpicturedb,movieratedb
    ports:
      - "5432:5432"

#    volumes:
#      - pgdata:/var/lib/postgresql/data
#
#volumes:
#  pgdata:
#    driver: local
