server:
  port: 8060

spring:

  jackson:
    default-property-inclusion: NON_NULL
    property-naming-strategy: SNAKE_CASE
    serialization.INDENT_OUTPUT: false
    serialization:
      write-dates-as-timestamps: true

  jpa:
    database: postgresql

  datasource:
    url: jdbc:postgresql://${db_ip:localhost}:${db_port:5432}/${db_name:movieratedb}
    username: ${db_username:root}
    password: ${db_password:root}

  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: group1
      properties:
        spring.json.trusted.packages: "*"

my:
  movie-rate:
    topic: movie_rate_topic
  top10:
    # Refresh materialized view and cache intervals, for test reasons I keep this times low, but they should be higher like 3m and 4m
    materialized-view:
      refresh-interval-ms: 10000
      keep-lock: 8s
    cache:
      refresh-interval-ms: 20000

management:
  server:
    port: 8061
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
