server:
  port: 8060

spring:
  # Resource server configurations
  #  security:
  #    oauth2:
  #      resourceserver:
  #        jwt:
  #          issuer-uri: http://localhost:8085/auth/realms/spring-security-example
  #          jwk-set-uri: http://localhost:8085/auth/realms/spring-security-example/protocol/openid-connect/certs

  jackson:
    default-property-inclusion: NON_NULL
    property-naming-strategy: SNAKE_CASE
    serialization.INDENT_OUTPUT: false
    serialization:
      write-dates-as-timestamps: true

  data:
    cassandra:
      keyspace-name: ratedb
      contact-points: 127.0.0.1
      local-datacenter: datacenter1

  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: group1
      properties:
        spring.json.trusted.packages: "*"

management:
  server:
    port: 8061
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
